export const headers = {
    'Appointments': [
        'Company',
        'Assign to',
        'Stage',
        'Appointment date & time',
        'Confirmed',
        'Name',
        'Contact',
        'Customer company',
        'Email',
        'DOB',
        'Address',
        'House Unit',
        'Postal Code',
        'Zone',
        '2 Name',
        '2 Contact',
        '2 Relationship',
        'AG no.',
        'Agreement date & time',
        'Products',
        'Total Price',
        'Discount',
        'Subtotal',
        'GST',
        'Grand Total',
        'Payments',
        'Total paid',
        'Outstanding',
        'Install / Maintenance',
        'Creator'
    ],
    'Appointments--Sales': [
        'Company',
        'Stage',
        'Appointment date & time',
        'Confirmed',
        'Name',
        'Contact',
        'Customer company',
        'Address',
        'House Unit',
        'Postal Code',
        'Zone',
        '2 Name',
        '2 Contact',
        '2 Relationship',
        'Products',
        'Total Price',
        'Discount',
        'Subtotal',
        'GST',
        'Grand Total',
    ],
    'Products': [
        'Priority',
        'Model',
        'Color',
        'Price',
        'Commission (sales)',
        'Commission (install)',
        'Creator'
    ],
    'Maintenance': [
        'Appointment name',
        'Job',
        'Unit',
        'Date & Time',
        'Confirmed',
        'Address & Zone',
        'Amount to collect',
        'Mode',
        'Status',
        'Assign to'
    ],
    'Payments': [
        'ID',
        'Payment Mode',
        'Amount',
        'Date',
        'Bank',
        'Detail',
        'Payment Status'
    ],
}

export const listLabels = {
    'Remarks': [
        'Date',
        'Text',
        'Creator',
    ],
    'Payments': [
        'ID',
        'Payment Mode',
        'Amount',
        'Date',
        'Bank',
        'Detail',
        'Payment Status'
    ],
    'Maintenance': [
        'Job',
        'Unit',
        'Date & Time',
        'Amount to collect',
        'Mode',
        'Status'
    ]
}